image: merklex/ether-test-base

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches

tests:
  stage: test
  script:
  - ./gradlew test
  artifacts:
    reports:
      junit: build/test-results/test/*.xml
